# Generated by Django 5.1.15 on 2026-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pgvector_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypricelog',
            name='logged_at',
            field=models.DateTimeField(db_index=True, help_text='UTC timestamp of the price observation.'),
        ),
        migrations.AlterField(
            model_name='dailypricelog',
            name='scrape_log_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the ScrapeLog row that produced this price entry.', null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='ean',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EAN-13 or EAN-8 barcode. Empty if unknown.', max_length=14),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of canonical image URLs (highest-quality source wins).'),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, help_text='Last time the matching pipeline updated this record.', null=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='manually_verified',
            field=models.BooleanField(default=False, help_text='Admin has manually confirmed this entity resolution.'),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='match_confidence',
            field=models.FloatField(default=1.0, help_text='RapidFuzz similarity score [0.0–1.0] from the last matching run. Scores below 0.85 are flagged for human review.'),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='mpn',
            field=models.CharField(blank=True, default='', help_text='Manufacturer Part Number.', max_length=128),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='name',
            field=models.CharField(db_index=True, help_text='Canonical product name as resolved by the matching pipeline.', max_length=512),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Freeform taxonomy tags derived from site listings.'),
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Latest scraped price in the site's currency.", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='match_score',
            field=models.FloatField(default=0.0, help_text='RapidFuzz score against the matched MasterProduct name.'),
        ),
    ]
