# Generated by Django 5.1.15 on 2026-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_admin', '0002_scrapelog_hypertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxypool',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code of the exit node.', max_length=2),
        ),
        migrations.AlterField(
            model_name='proxypool',
            name='endpoint',
            field=models.CharField(help_text='Full proxy DSN: http://user:pass@host:port', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='proxypool',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to immediately remove from worker rotation.'),
        ),
        migrations.AlterField(
            model_name='proxypool',
            name='provider',
            field=models.CharField(blank=True, default='', help_text="Provider name, e.g. 'BrightData', 'Oxylabs'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='scrapedurl',
            name='arq_job_id',
            field=models.CharField(blank=True, default='', help_text='Arq job ID currently processing this URL, if any.', max_length=128),
        ),
        migrations.AlterField(
            model_name='scrapedurl',
            name='next_scrape_after',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Earliest time this URL should be re-scraped.  NULL = immediately.', null=True),
        ),
        migrations.AlterField(
            model_name='scrapedurl',
            name='priority',
            field=models.SmallIntegerField(db_index=True, default=0, help_text='Higher = scraped sooner.  Use negative values to deprioritise.'),
        ),
        migrations.AlterField(
            model_name='scrapedurl',
            name='url',
            field=models.URLField(db_index=True, help_text='Fully-qualified product or category page URL.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='elapsed_seconds',
            field=models.FloatField(help_text='Total request duration including retries.'),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='fetched_at',
            field=models.DateTimeField(db_index=True, help_text='UTC timestamp when the fetch completed.'),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='final_url',
            field=models.URLField(blank=True, default='', help_text='Final URL after all redirects.', max_length=2048),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='proxy_used',
            field=models.CharField(blank=True, default='', help_text='Obfuscated proxy DSN used for this request.', max_length=256),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='r2_bronze_key',
            field=models.CharField(blank=True, default='', help_text='Cloudflare R2 object key for the raw .jsonl.gz Bronze file produced by this fetch.', max_length=512),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='url',
            field=models.URLField(help_text='Exact URL fetched (may differ from ScrapedURL after redirects).', max_length=2048),
        ),
        migrations.AlterField(
            model_name='scrapelog',
            name='worker_hostname',
            field=models.CharField(blank=True, default='', help_text='Docker container / hostname that ran this job.', max_length=128),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='base_url',
            field=models.URLField(help_text='Root URL of the target site, e.g. https://example.com', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='category_url_patterns',
            field=models.JSONField(blank=True, default=list, help_text='List of regex patterns matching category/listing page URLs that the discoverer should follow.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='domain',
            field=models.CharField(db_index=True, help_text='Bare hostname used for per-domain semaphore keying, e.g. example.com', max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='impersonate_profile',
            field=models.CharField(default='chrome', help_text='curl_cffi browser impersonation profile override for this site. Defaults to the global SCRAPER_IMPERSONATE_PROFILE env var.', max_length=32),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='max_concurrency',
            field=models.PositiveSmallIntegerField(default=5, help_text='Max simultaneous Arq workers hitting this domain. Hard cap per CLAUDE.md §4 is 5 — do not exceed without review.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum fetch retry attempts per URL.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='name',
            field=models.CharField(help_text="Human-readable site name, e.g. 'Pharma Plus FR'", max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal ops notes — anti-bot measures, quirks, contact info.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='product_url_patterns',
            field=models.JSONField(blank=True, default=list, help_text='List of regex patterns identifying product detail page URLs.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='request_delay_ms',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum delay between sequential requests to this domain (ms).'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='retry_backoff_base_seconds',
            field=models.FloatField(default=5.0, help_text='Base seconds for exponential back-off on retries.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sitemap_url',
            field=models.URLField(blank=True, default='', help_text='Primary sitemap URL for the URL discoverer, if available.', max_length=512),
        ),
    ]
