# Generated by Django 5.1.15 on 2026-06-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_admin', '0003_alter_proxypool_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxypool',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Restrict this proxy to specific sites. Leave empty to make it available to all sites.', related_name='proxies', to='scraper_admin.siteconfig'),
        ),
    ]
