# Generated by Django 5.1.15 on 2026-06-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grossiste', '0001_initial'),
        ('products', '0007_dailypricelog_set_null_fks'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grossisteproduct',
            name='unique_grossiste_product_code',
        ),
        migrations.AlterField(
            model_name='grossisteconfig',
            name='domain',
            field=models.URLField(help_text='Base URL, e.g. https://gpm.ma', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='grossisteconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grossisteconfig',
            name='name',
            field=models.CharField(help_text="Human-readable name, e.g. 'GPM', 'COPHARM', 'SOMAPHARM'", max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='grossisteconfig',
            name='password',
            field=models.CharField(help_text='Stored in plaintext — use environment variable injection in production.', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='external_order_id',
            field=models.CharField(blank=True, default='', help_text='Order ID returned by the grossiste API', max_length=256),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='response_payload',
            field=models.JSONField(blank=True, help_text='Full API response for debugging', null=True),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Prix pharmacien at time of order', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='code',
            field=models.CharField(db_index=True, help_text='CODE_PRODU — unique product code within this grossiste', max_length=32),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='forme',
            field=models.CharField(blank=True, default='', help_text='FORME_PROD — dosage form code (CO, GE, SI, GO, SP, …)', max_length=8),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='in_stock',
            field=models.BooleanField(blank=True, default=None, help_text='None = not yet checked', null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='manually_verified',
            field=models.BooleanField(default=False, help_text='Tick after manually confirming the MasterProduct link is correct.'),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='master_product',
            field=models.ForeignKey(blank=True, help_text='Linked MasterProduct — populated by the matching pipeline. NULL means not yet matched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grossiste_products', to='products.masterproduct'),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='match_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score from the matching pipeline (0–1).', null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='name',
            field=models.CharField(help_text='NOM_PRODUI', max_length=512),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='pa',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="PA — prix d'achat (often empty)", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='ppm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PPM — prix public maximum / max legal retail price (MAD)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='prix_pharmacien',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='PRIX_PHAR — pharmacy buy price (MAD excl. tax)', max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grossisteproduct',
            unique_together={('grossiste', 'code')},
        ),
    ]
