# Generated by Django 5.1.15 on 2026-06-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grossiste', '0002_remove_grossisteproduct_unique_grossiste_product_code_and_more'),
        ('grossiste', '0003_remove_credentials'),
    ]

    operations = [
    ]
