# Generated by Django 5.1.15 on 2026-06-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grossiste', '0005_update_grossisteorder'),
        ('products', '0007_dailypricelog_set_null_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grossisteconfig',
            name='password',
        ),
        migrations.AlterField(
            model_name='grossisteconfig',
            name='domain',
            field=models.URLField(help_text='Base URL of the grossiste site, e.g. https://gpm.ma', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='grossisteconfig',
            name='name',
            field=models.CharField(help_text="Identifier, e.g. 'GPM', 'Sophasais', 'Lodimed'", max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='response_payload',
            field=models.JSONField(blank=True, help_text='Full Sobrus API response', null=True),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — not yet submitted'), ('submitted', 'Submitted to Sobrus'), ('confirmed', 'Confirmed by grossiste'), ('failed', 'Submission failed')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='grossisteorder',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Prix pharmacien / purchase price at time of order', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='code',
            field=models.CharField(db_index=True, help_text='CODE_PRODU', max_length=32),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='forme',
            field=models.CharField(blank=True, default='', help_text='FORME_PROD — dosage form code', max_length=8),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='manually_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='master_product',
            field=models.ForeignKey(blank=True, help_text='Linked MasterProduct — populated by the matching pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grossiste_products', to='products.masterproduct'),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='ppm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PPM — prix public maximum (MAD)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='prix_pharmacien',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='PRIX_PHAR — pharmacy buy price (MAD)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='grossisteproduct',
            name='sobrus_product_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Sobrus internal product ID used in api.pharma.sobrus.com/purchaseorders/check-availability. Fetched via Sobrus API.', null=True),
        ),
        migrations.AddIndex(
            model_name='grossisteproduct',
            index=models.Index(fields=['sobrus_product_id'], name='idx_gros_sobrus_id'),
        ),
    ]
